name: Server CI

on:
  push:
    branches:
      - master
    paths:
      - 'server/**.go'
  pull_request:
    branches:
      - master
    paths:
      - 'server/**.go'

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      
      - name: Run golangci-lint
        run: golangci-lint run -v

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint 

    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./tests/... -v 